---
- name: Install Apache, mariadb and php
  hosts: 192.168.10.205
  tasks:
  - name: Disable the firewalld service
    service:
      name: firewalld
      state: stopped
  - name: Disable selinux
    shell: setenforce 0
  - name: Disable Selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: 'SELINUX=enforcing'
      line: 'SELINUX=disabled'
  - name: Install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - httpd
      - mariadb
      - mariadb-server
      - MySQL-python
      - php
      - php-mysql
      - php-fpm
  - name: Start all the packages
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - mariadb

  - name: Download repo
    command: rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
    ignore_errors: yes
  - name: Install zabbix
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-agent
  - name: Create database
    mysql_db:
      name: zabbix
      state: present
      encoding: utf8
  - name: Create zabbix user
    mysql_user:
      name: zabbix
      password: 'password'
      priv: 'zabbix.*:ALL,GRANT'
      host: localhost
      state: present
  - name: Setup schema and import the data
    shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -ppassword zabbix
  - name: Configure zabbix_server
    lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# DBPassword='
      line: 'DBPassword=password'
  - name: Configure zabbix.conf
    lineinfile:
      path: /etc/httpd/conf.d/zabbix.conf
      regexp: '# php_value date.timezone Europe/Riga'
      line: '        php_value date.timezone Asia/Kolkata'
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
  - name: Start zabbix-server
    service:
      name: zabbix-server
      state: started
      enabled: yes

